# Possible decks
class Standard52CardDeck:
    def __init__(self):
        self.deck = [
            # Jokers
            ("Joker", "assets/simple_jk_b.png"),
            ("Joker", "assets/simple_jk_r.png"),
            # Spades
            ("2 of Spades", "assets/simple_s_2.png"),
            ("3 of Spades", "assets/simple_s_3.png"),
            ("4 of Spades", "assets/simple_s_4.png"),
            ("5 of Spades", "assets/simple_s_5.png"),
            ("6 of Spades", "assets/simple_s_6.png"),
            ("7 of Spades", "assets/simple_s_7.png"),
            ("8 of Spades", "assets/simple_s_8.png"),
            ("9 of Spades", "assets/simple_s_9.png"),
            ("10 of Spades", "assets/simple_s_10.png"),
            ("Jack of Spades", "assets/simple_s_j.png"),
            ("Queen of Spades", "assets/simple_s_q.png"),
            ("King of Spades", "assets/simple_s_k.png"),
            ("Ace of Spades", "assets/simple_s_a.png"),
            # Hearts
            ("2 of Hearts", "assets/simple_h_2.png"),
            ("3 of Hearts", "assets/simple_h_3.png"),
            ("4 of Hearts", "assets/simple_h_4.png"),
            ("5 of Hearts", "assets/simple_h_5.png"),
            ("6 of Hearts", "assets/simple_h_6.png"),
            ("7 of Hearts", "assets/simple_h_7.png"),
            ("8 of Hearts", "assets/simple_h_8.png"),
            ("9 of Hearts", "assets/simple_h_9.png"),
            ("10 of Hearts", "assets/simple_h_10.png"),
            ("Jack of Hearts", "assets/simple_h_j.png"),
            ("Queen of Hearts", "assets/simple_h_q.png"),
            ("King of Hearts", "assets/simple_h_k.png"),
            ("Ace of Hearts", "assets/simple_h_a.png"),
            # Diamonds
            ("2 of Diamonds", "assets/simple_d_2.png"),
            ("3 of Diamonds", "assets/simple_d_3.png"),
            ("4 of Diamonds", "assets/simple_d_4.png"),
            ("5 of Diamonds", "assets/simple_d_5.png"),
            ("6 of Diamonds", "assets/simple_d_6.png"),
            ("7 of Diamonds", "assets/simple_d_7.png"),
            ("8 of Diamonds", "assets/simple_d_8.png"),
            ("9 of Diamonds", "assets/simple_d_9.png"),
            ("10 of Diamonds", "assets/simple_d_10.png"),
            ("Jack of Diamonds", "assets/simple_d_j.png"),
            ("Queen of Diamonds", "assets/simple_d_q.png"),
            ("King of Diamonds", "assets/simple_d_k.png"),
            ("Ace of Diamonds", "assets/simple_d_a.png"),
            # Clubs
            ("2 of Clubs", "assets/simple_c_2.png"),
            ("3 of Clubs", "assets/simple_c_3.png"),
            ("4 of Clubs", "assets/simple_c_4.png"),
            ("5 of Clubs", "assets/simple_c_5.png"),
            ("6 of Clubs", "assets/simple_c_6.png"),
            ("7 of Clubs", "assets/simple_c_7.png"),
            ("8 of Clubs", "assets/simple_c_8.png"),
            ("9 of Clubs", "assets/simple_c_9.png"),
            ("10 of Clubs", "assets/simple_c_10.png"),
            ("Jack of Clubs", "assets/simple_c_j.png"),
            ("Queen of Clubs", "assets/simple_c_q.png"),
            ("King of Clubs", "assets/simple_c_k.png"),
            ("Ace of Clubs", "assets/simple_c_a.png")
        ]
        
        self.blackjack = [ # Does not include jokers
            # Spades
            ("2 of Spades", "assets/simple_s_2.png", 2),
            ("3 of Spades", "assets/simple_s_3.png", 3),
            ("4 of Spades", "assets/simple_s_4.png", 4),
            ("5 of Spades", "assets/simple_s_5.png", 5),
            ("6 of Spades", "assets/simple_s_6.png", 6),
            ("7 of Spades", "assets/simple_s_7.png", 7),
            ("8 of Spades", "assets/simple_s_8.png", 8),
            ("9 of Spades", "assets/simple_s_9.png", 9),
            ("10 of Spades", "assets/simple_s_10.png", 10),
            ("Jack of Spades", "assets/simple_s_j.png", 10),
            ("Queen of Spades", "assets/simple_s_q.png", 10),
            ("King of Spades", "assets/simple_s_k.png", 10),
            ("Ace of Spades", "assets/simple_s_a.png", (1, 11)),
            # Hearts
            ("2 of Hearts", "assets/simple_h_2.png", 2),
            ("3 of Hearts", "assets/simple_h_3.png", 3),
            ("4 of Hearts", "assets/simple_h_4.png", 4),
            ("5 of Hearts", "assets/simple_h_5.png", 5),
            ("6 of Hearts", "assets/simple_h_6.png", 6),
            ("7 of Hearts", "assets/simple_h_7.png", 7),
            ("8 of Hearts", "assets/simple_h_8.png", 8),
            ("9 of Hearts", "assets/simple_h_9.png", 9),
            ("10 of Hearts", "assets/simple_h_10.png", 10),
            ("Jack of Hearts", "assets/simple_h_j.png", 10),
            ("Queen of Hearts", "assets/simple_h_q.png", 10),
            ("King of Hearts", "assets/simple_h_k.png", 10),
            ("Ace of Hearts", "assets/simple_h_a.png", (1, 11)),
            # Diamonds
            ("2 of Diamonds", "assets/simple_d_2.png", 2),
            ("3 of Diamonds", "assets/simple_d_3.png", 3),
            ("4 of Diamonds", "assets/simple_d_4.png", 4),
            ("5 of Diamonds", "assets/simple_d_5.png", 5),
            ("6 of Diamonds", "assets/simple_d_6.png", 6),
            ("7 of Diamonds", "assets/simple_d_7.png", 7),
            ("8 of Diamonds", "assets/simple_d_8.png", 8),
            ("9 of Diamonds", "assets/simple_d_9.png", 9),
            ("10 of Diamonds", "assets/simple_d_10.png", 10),
            ("Jack of Diamonds", "assets/simple_d_j.png", 10),
            ("Queen of Diamonds", "assets/simple_d_q.png", 10),
            ("King of Diamonds", "assets/simple_d_k.png", 10),
            ("Ace of Diamonds", "assets/simple_d_a.png", (1, 11)),
            # Clubs
            ("2 of Clubs", "assets/simple_c_2.png", 2),
            ("3 of Clubs", "assets/simple_c_3.png", 3),
            ("4 of Clubs", "assets/simple_c_4.png", 4),
            ("5 of Clubs", "assets/simple_c_5.png", 5),
            ("6 of Clubs", "assets/simple_c_6.png", 6),
            ("7 of Clubs", "assets/simple_c_7.png", 7),
            ("8 of Clubs", "assets/simple_c_8.png", 8),
            ("9 of Clubs", "assets/simple_c_9.png", 9),
            ("10 of Clubs", "assets/simple_c_10.png", 10),
            ("Jack of Clubs", "assets/simple_c_j.png", 10),
            ("Queen of Clubs", "assets/simple_c_q.png", 10),
            ("King of Clubs", "assets/simple_c_k.png", 10),
            ("Ace of Clubs", "assets/simple_c_a.png", (1, 11)),
        ]